// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/api_req.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateApiReqFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package req


type `)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`Req struct {
    `)
	for _, field := range m.RequestFields {
		buffer.WriteString("\n\t")
		buffer.WriteString(field)
	}
	buffer.WriteString(`
}`)

}
