// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/api_register_module.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateApiRegisterModuleFile(m *project.Metadata, buffer *bytes.Buffer) {
	hero.EscapeHTML(m.ModuleName, buffer)
	buffer.WriteString(`RouteGroup := ecot.RouteGroup{
	    Routes:[]ecot.Route{
            {Method: echo.POST, Path:"", Handler:Create`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`},
            {Method: echo.GET, Path:"/:id", Handler:Get`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`},
            {Method: echo.GET, Path:"", Handler:Find`)
	hero.EscapeHTML(m.ModuleTitleNamePlural, buffer)
	buffer.WriteString(`},
            {Method: echo.PUT, Path:"/:id", Handler:Update`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`},
		},
	}
	m["/`)
	hero.EscapeHTML(m.ModuleNamePlural, buffer)
	buffer.WriteString(`"] = `)
	hero.EscapeHTML(m.ModuleName, buffer)
	buffer.WriteString(`RouteGroup

`)

}
