// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/api_resp.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateApiRespFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package resp


type `)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`Resp struct {
    `)
	for _, field := range m.ResponseFields {
		buffer.WriteString("\n\t")
		buffer.WriteString(field)
	}
	buffer.WriteString(`
}`)

}
