// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/api_register.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateApiRegisterFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package api

import (
	"github.com/labstack/echo"
	"github.com/uauteam/ecot"
)

func Register()map[string]ecot.RouteGroup {
	m := make(map[string]ecot.RouteGroup)

	`)
	hero.EscapeHTML(m.ModuleName, buffer)
	buffer.WriteString(`RouteGroup := ecot.RouteGroup{
        Routes:[]ecot.Route{
            {Method: echo.POST, Path:"", Handler:Create`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`, Version:"v1"},
            {Method: echo.GET, Path:"/:id", Handler:Get`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`, Version:"v1"},
            {Method: echo.GET, Path:"", Handler:Find`)
	hero.EscapeHTML(m.ModuleTitleNamePlural, buffer)
	buffer.WriteString(`, Version:"v1"},
            {Method: echo.PUT, Path:"/:id", Handler:Update`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`, Version:"v1"},
        },
    }
    m["/`)
	hero.EscapeHTML(m.ModuleNamePlural, buffer)
	buffer.WriteString(`"] = `)
	hero.EscapeHTML(m.ModuleName, buffer)
	buffer.WriteString(`RouteGroup

	return m
}`)

}
