// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/api_query.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateApiQueryFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package query

import "github.com/uauteam/ecot/dto/qry"

type `)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`Query struct {
    qry.PageQuery

    `)
	for _, field := range m.QueryFields {
		buffer.WriteString("\n\t")
		buffer.WriteString(field)
	}
	buffer.WriteString(`
}`)

}
