// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/app_global.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateAppGlobalFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package app

var Name = "`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(`"`)

}
