// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/entity.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateEntityFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package entity

import (
	"github.com/jinzhu/gorm"
	"`)
	hero.EscapeHTML(m.RepoHost, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoUser, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(`/app"
)

// module model struct
type `)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(` struct {
	gorm.Model
	`)
	for _, field := range m.EntityFields {
		buffer.WriteString("\n\t")
		buffer.WriteString(field)
	}
	buffer.WriteString(`
}

// the database name of the modle struct(table)
func (`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`) DBName()string {
	return "db_" + app.Name
}

// fields that will be ignored when creating or updating the struct
// e.g. []string{"username", "email", "password"}
func (`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`) ProtectedFields()[]string{
	return `)
	buffer.WriteString(m.ProtectedFieldsStr)
	buffer.WriteString(`
}`)

}
