// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/git_ignore.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"
)

func GenerateGitIgnoreFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
.idea
*.db`)

}
