// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/main.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateMainFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package main

import (
	`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(` "`)
	hero.EscapeHTML(m.RepoHost, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoUser, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(`/config"
	"github.com/uauteam/ecot"
)

func main() {

	e := ecot.New()

	if err := e.Register(`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(`.Config); err != nil {
		e.Logger.Fatal(err)
	}

	e.Logger.Fatal(e.Start(":1323"))
}`)

}
