// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/repo_database.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateRepoDatabaseFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
package repo

import "`)
	hero.EscapeHTML(m.RepoHost, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoUser, buffer)
	buffer.WriteString(`/`)
	hero.EscapeHTML(m.RepoName, buffer)
	buffer.WriteString(`/entity"

func AutoMigrateEntityRegister()(entities []interface{}) {

	entities = append(entities, &entity.`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`{})

	return
}`)

}
