// Code generated by hero.
// source: /Users/kingphang/Workspaces/uau/ebot/template/repo_database_module.tpl
// DO NOT EDIT!
package template

import (
	"bytes"
	"github.com/uauteam/ebot/project"

	"github.com/shiyanhui/hero"
)

func GenerateRepoDatabaseModuleFile(m *project.Metadata, buffer *bytes.Buffer) {
	buffer.WriteString(`
	entities = append(entities, &entity.`)
	hero.EscapeHTML(m.ModuleTitleName, buffer)
	buffer.WriteString(`{})

`)

}
